import fs from "fs";
import chalk from "chalk";

export const generateTypes = async () => {
  if (!fs.existsSync("env.spec.json")) {
    console.log(chalk.red("❌ Missing env.spec.json. Run `smart-env-helper init` first."));
    return;
  }

  const spec = JSON.parse(fs.readFileSync("env.spec.json", "utf8"));
  let output = `// Auto-generated by smart-env-helper\nexport const env = {\n`;

  for (const [key, type] of Object.entries(spec)) {
    output += `  ${key}: process.env.${key} as ${type},\n`;
  }

  output += "};\n";

  fs.writeFileSync("src/env.ts", output);
  console.log(chalk.green("✅ env.ts generated successfully!"));
};
